### ISSUE TITLE
How to use template, or specify --outputfile.

### ISSUE THREAD

**Issue by fachizel** [sbraz/pymediainfo#113]
Hey I'm wondering if there is some way to specify a template file to use?

`mediainfo --Output=file:///template.txt --LogFile=mediinfo.nfo *.mp4`

is this possible?

this is a sample template file: 
https://0bin.net/paste/QQo4gmjf#U1OgZpRC6G2vQtGKfWwpEiGjP0nF2F4WmVWcLDF5H2Z

**Comment by sbraz** [comment]
Hi,
The `output` options is well documented, I'm surprised you didn't see it [here](https://pymediainfo.readthedocs.io/en/stable/pymediainfo.html).

The following works but I would advise you to use a more pythonic templating language like Jinja2 instead of relying on MediaInfo's which seems to be rather simplistic and limited (and also doesn't seem to handle errors very well).

```py
#!/usr/bin/env python3

import pymediainfo

print(pymediainfo.MediaInfo.parse("file.mp4", output="file://template.txt"))
```
