### ISSUE TITLE
OSError loading libmediainfo.so with pymediainfo 2.0 

### ISSUE THREAD

**Issue by rlskoeser** [sbraz/pymediainfo#19]
I'm getting an error trying to use the latest version (I'm guessing it's related to #14 ?).

I don't see anything in the documentation about how libmediainfo needs to be installed, or if it matters what version.

```
>>> MediaInfo.parse(filename)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/httpd/sites/keep/keep-2.6.1/env/lib/python2.7/site-packages/pymediainfo/__init__.py", line 86, in parse
    lib = CDLL("libmediainfo.so.0")
  File "/opt/rh/python27/root/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libmediainfo.so.0: undefined symbol: _ZN6ZenLib6Ztring22Date_From_Seconds_1904Ej
```

This is on Red Hat Enterprise Linux Server release 6.7 (Santiago).

**Comment by sbraz** [comment]
Well, the documentation states that MediaInfo must be installed. If it is, the lib is installed as well :)
I'll update the doc to make it more clear.
As for your error, I don't think it's related to pymediainfo but rather to libzen on which mediainfo and its lib depend. Can you run the mediainfo binary?

**Comment by rlskoeser** [comment]
I thought sure I had tested it, but I see now that I'm getting the same error when I run mediainfo on the command line.  So, clearly this was an issue with the mediainfo install.  I guess the package dependencies were configured wrong, it looks like libzen didn't get installed with it.  We put that on the system and now it's working fine both on the command line and through python.  

I knew the library had to be installed. :-) I just wasn't sure if there were any more specifics than that, different versions of libmediainfo or anything like that.

Thanks so much for the swift response.  Sorry for assuming the issue was with the new version of pymediainfo!

**Comment by devxpy** [comment]
@sbraz  Can we have this as a check while installing?

**Comment by sbraz** [comment]
@devxpy I'm not sure how you would like to proceed. AFAIK other similar libraries do not have any requirement set at install time. I guess that those linking to libraries fail to build while those using ctypes like python-magic or pymediainfo will just fail at runtime.
If you're installing pymediainfo via [one of the existing packages](https://repology.org/metapackage/python:pymediainfo/versions), you shouldn't have to worry about that.
What's more, pymediainfo can be used to load XML files generated by MediaInfo elsewhere so the library isn't a hard requirement, that's why this function was added:
https://github.com/sbraz/pymediainfo/blob/b773cb5bfa32dcd9bcfbddf5f7ee1f558a7eeee2/pymediainfo/__init__.py#L157
