### ISSUE TITLE
[Question]  How to discover commands?

### ISSUE THREAD

**Issue by codenotworking** [sbraz/pymediainfo#86]
I'm new to pymediainfo.  I've read that it's a wrapper for MediaInfo.  I'm trying to learn how I can discover the commands that pymediainfo uses to execute the MediaInfo commands.

I use the CLI version of MediaInfo.  Now I want to implement it with Python.

Here is the CLI I use to get the play time in XXh YYm format:
```mediainfo.exe --inform="Video;%Duration/String%" "video.mkv"```

This will give me something like this: `1 h 48 min`

I have a basic idea of some of the commands, from reading some of the issues on here.  For example:
```
from pymediainfo import MediaInfo

media = MediaInfo.parse(r"video.mkv")

for track in media.tracks:
    if track.track_type == "Video":
        print(track.duration)
```

Unfortunately, I have no idea how I can discover the commands pymediainfo uses.  Specifically, how do I access the Python commands that would execute the "string" commands in MediaInfo, such as `Video;%Duration/String1%` or `Video;%BitRate/String%`?

**Comment by sbraz** [comment]
Hi, the [latest version of the documentation](https://pymediainfo.readthedocs.io/en/latest/#using-mediainfo) includes one more example that showcases the `to_data` method which basically converts a `MediaInfo` or `Track` attribute to `dict`, making it very easy to analyse.

As for "string" attributes, they are always prefixed with `other_`. I have just updated the documentation to mention that in the index (it was already explained [in the doc for `Track` object](https://pymediainfo.readthedocs.io/en/latest/pymediainfo.html#pymediainfo.Track)).


There is also [the demo script](https://github.com/sbraz/pymediainfo/blob/master/demo.py).
This should be enough for you to start finding the corresponding values for the attributes you need.

If you really want to use the `Inform` parameters, you'll want the `output` parameter of the `parse` method, documented [here](https://pymediainfo.readthedocs.io/en/latest/pymediainfo.html#pymediainfo.MediaInfo.parse):

However, I would not recommend it because:
* using this means parsing the same file several times, it is not efficient
* if you have several track of the same time, the output will look weird

**Comment by codenotworking** [comment]
Thanks for tips.  I reviewed the example in your first link ([Using MediaInfo](https://pymediainfo.readthedocs.io/en/latest/#using-mediainfo)), and noticed the command `pprint(track.to_data())`, which is what I was really looking for.  That helps me discover the commands I want to use.
